# These are supported funding model platforms

custom: ['https://github.com/ist3d', 'https://github.com/rether911', 'https://github.com/ioSphinx', 'http://news.rr.nihalnavath.com/posts/somegithubstuff-20fc0b23']
